// Auto-generated species photo URLs from iNaturalist
// 60/60 species with photos

export const SPECIES_PHOTOS: Record<string, string | null> = {
  "Pelecanus occidentalis": "https://inaturalist-open-data.s3.amazonaws.com/photos/74013719/medium.jpg",
  "Danaus plexippus": "https://inaturalist-open-data.s3.amazonaws.com/photos/227923335/medium.jpeg",
  "Pandion haliaetus": "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg",
  "Nycticorax nycticorax": "https://inaturalist-open-data.s3.amazonaws.com/photos/29852324/medium.jpg",
  "Nannopterum auritum": "https://inaturalist-open-data.s3.amazonaws.com/photos/182713821/medium.jpg",
  "Bahiopsis laciniata": "https://static.inaturalist.org/photos/73929529/medium.jpeg",
  "Larus heermanni": "https://static.inaturalist.org/photos/478385/medium.jpg",
  "Ceanothus verrucosus": "https://inaturalist-open-data.s3.amazonaws.com/photos/69908258/medium.jpeg",
  "Apodemia virgulti": "https://inaturalist-open-data.s3.amazonaws.com/photos/90583/medium.jpg",
  "Pinus torreyana": "https://inaturalist-open-data.s3.amazonaws.com/photos/475593552/medium.jpg",
  "Quercus engelmannii": "https://static.inaturalist.org/photos/523581/medium.JPG",
  "Pelecanus occidentalis californicus": "https://inaturalist-open-data.s3.amazonaws.com/photos/178182099/medium.jpg",
  "Xylorhiza orcuttii": "https://inaturalist-open-data.s3.amazonaws.com/photos/32301830/medium.jpg",
  "Calochortus weedii": "https://inaturalist-open-data.s3.amazonaws.com/photos/206027894/medium.jpg",
  "Limonium perezii": "https://inaturalist-open-data.s3.amazonaws.com/photos/266306575/medium.jpg",
  "Leptosyne maritima": "https://inaturalist-open-data.s3.amazonaws.com/photos/184416325/medium.jpeg",
  "Crotalus ruber": "https://static.inaturalist.org/photos/31514726/medium.jpg",
  "Phrynosoma blainvillii": "https://static.inaturalist.org/photos/17666641/medium.jpg",
  "Falco peregrinus": "https://inaturalist-open-data.s3.amazonaws.com/photos/212499566/medium.jpg",
  "Quercus dumosa": "https://inaturalist-open-data.s3.amazonaws.com/photos/242352501/medium.jpeg",
  "Charadrius vociferus": "https://inaturalist-open-data.s3.amazonaws.com/photos/15053771/medium.jpg",
  "Cylindropuntia fosbergii": "https://inaturalist-open-data.s3.amazonaws.com/photos/35178409/medium.jpg",
  "Aspidoscelis hyperythrus": "https://static.inaturalist.org/photos/4078283/medium.jpg",
  "Bergerocactus emoryi": "https://inaturalist-open-data.s3.amazonaws.com/photos/17865606/medium.jpg",
  "Selaginella cinerascens": "https://inaturalist-open-data.s3.amazonaws.com/photos/58293492/medium.jpeg",
  "Egretta rufescens": "https://inaturalist-open-data.s3.amazonaws.com/photos/1954331/medium.jpg",
  "Adolphia californica": "https://inaturalist-open-data.s3.amazonaws.com/photos/93280/medium.jpg",
  "Calidris minutilla": "https://inaturalist-open-data.s3.amazonaws.com/photos/230314/medium.jpg",
  "Circus hudsonius": "https://inaturalist-open-data.s3.amazonaws.com/photos/114355770/medium.jpg",
  "Calypte costae": "https://inaturalist-open-data.s3.amazonaws.com/photos/255450373/medium.jpg",
  "Tringa melanoleuca": "https://inaturalist-open-data.s3.amazonaws.com/photos/48630238/medium.jpeg",
  "Thalasseus elegans": "https://inaturalist-open-data.s3.amazonaws.com/photos/56468/medium.jpg",
  "Pluvialis squatarola": "https://static.inaturalist.org/photos/10603462/medium.jpg",
  "Rallus obsoletus": "https://inaturalist-open-data.s3.amazonaws.com/photos/2197206/medium.jpg",
  "Euphorbia misera": "https://static.inaturalist.org/photos/14262525/medium.jpg",
  "Brodiaea orcuttii": "https://static.inaturalist.org/photos/76577065/medium.jpeg",
  "Artemisia palmeri": "https://inaturalist-open-data.s3.amazonaws.com/photos/324838320/medium.jpg",
  "Dudleya saxosa aloides": "https://inaturalist-open-data.s3.amazonaws.com/photos/6313485/medium.jpg",
  "Bombus sonorus": "https://inaturalist-open-data.s3.amazonaws.com/photos/445519217/medium.jpg",
  "Spea hammondii": "https://static.inaturalist.org/photos/12739833/medium.jpg",
  "Anarhynchus nivosus": "https://inaturalist-open-data.s3.amazonaws.com/photos/227950/medium.jpg",
  "Helminthoglypta tudiculata": "https://static.inaturalist.org/photos/13902921/medium.jpg",
  "Clematis pauciflora": "https://inaturalist-open-data.s3.amazonaws.com/photos/62202866/medium.jpg",
  "Amazona viridigenalis": "https://inaturalist-open-data.s3.amazonaws.com/photos/59186054/medium.jpeg",
  "Haliaeetus leucocephalus": "https://inaturalist-open-data.s3.amazonaws.com/photos/349074095/medium.jpeg",
  "Bombus crotchii": "https://inaturalist-open-data.s3.amazonaws.com/photos/408403673/medium.jpg",
  "Apostichopus parvimensis": "https://inaturalist-open-data.s3.amazonaws.com/photos/19669029/medium.jpg",
  "Haliotis fulgens": "https://inaturalist-open-data.s3.amazonaws.com/photos/6515542/medium.jpg",
  "Pseudobatos productus": "https://inaturalist-open-data.s3.amazonaws.com/photos/2441883/medium.jpg",
  "Hypanus dipterurus": "https://inaturalist-open-data.s3.amazonaws.com/photos/351417853/medium.jpg",
  "Bodianus pulcher": "https://inaturalist-open-data.s3.amazonaws.com/photos/106228676/medium.jpg",
  "Panoquina errans": "https://static.inaturalist.org/photos/2345029/medium.jpg",
  "Ensatina eschscholtzii klauberi": "https://static.inaturalist.org/photos/6071278/medium.jpg",
  "Stereolepis gigas": "https://static.inaturalist.org/photos/8768054/medium.jpg",
  "Cyprinodon macularius": "https://inaturalist-open-data.s3.amazonaws.com/photos/167143095/medium.jpg",
  "Texosporium sancti-jacobi": "https://inaturalist-open-data.s3.amazonaws.com/photos/9734096/medium.jpg",
  "Niebla ceruchis": "https://inaturalist-open-data.s3.amazonaws.com/photos/8859254/medium.jpeg",
  "Niebla cephalota": "https://inaturalist-open-data.s3.amazonaws.com/photos/243982/medium.jpg",
  "Placynthiella oligotropha": "https://inaturalist-open-data.s3.amazonaws.com/photos/20978787/medium.jpg",
  "Turbinellus kauffmanii": "https://static.inaturalist.org/photos/26142567/medium.jpeg"
};
